options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE
  dynamic_substitutions: true
  machineType: E2_HIGHCPU_8

steps:
- name: node:24-alpine
  id: "install"
  entrypoint: sh
  args:
    - "-c"
    - |
      npm ci

- name: node:24-alpine
  id: "build-backend"
  entrypoint: sh
  args:
    - "-c"
    - |
      npx nx build daypuzzlesolver -c production

- name: node:24-alpine
  id: "build-frontend"
  entrypoint: sh
  args:
    - "-c"
    - |
      npx nx build daypuzzleui --configuration=production

- name: gcr.io/cloud-builders/docker
  id: "docker-backend"
  args:
    - build
    - "-f"
    - "Dockerfile.backend"
    - "-t"
    - "europe-west1-docker.pkg.dev/$PROJECT_ID/app/backend:$COMMIT_SHA"
    - "."

- name: gcr.io/cloud-builders/docker
  id: "docker-frontend"
  args:
    - build
    - "-f"
    - "Dockerfile.frontend"
    - "-t"
    - "europe-west1-docker.pkg.dev/$PROJECT_ID/app/frontend:$COMMIT_SHA"
    - "."

- name: gcr.io/cloud-builders/docker
  id: "push-backend"
  args: ["push", "europe-west1-docker.pkg.dev/$PROJECT_ID/app/backend:$COMMIT_SHA"]

- name: gcr.io/cloud-builders/docker
  id: "push-frontend"
  args: ["push", "europe-west1-docker.pkg.dev/$PROJECT_ID/app/frontend:$COMMIT_SHA"]

# 7. Terraform init
- name: 'hashicorp/terraform:1.6.7'
  id: 'terraform-init'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      cd terraform
      terraform init

# 8. Terraform plan
- name: 'hashicorp/terraform:1.6.7'
  id: 'terraform-plan'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      cd terraform
      terraform plan -out=tfplan

# 9. Terraform apply
- name: 'hashicorp/terraform:1.6.7'
  id: 'terraform-apply'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      cd terraform
      terraform apply -auto-approve tfplan

timeout: "1800s"

images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/app/backend:$COMMIT_SHA"
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/app/frontend:$COMMIT_SHA"
