# Runtime Dockerfile for frontend. Expects built output at dist/apps/daypuzzleui/browser
FROM nginx:alpine

# Remove default nginx index if present
RUN rm -rf /usr/share/nginx/html/*

COPY dist/apps/daypuzzleui/browser /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
